apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.app }}
spec:
  ports:
  - port: 1111
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.app }}
  type: NodePort
status:
  loadBalancer: {}
